"""Record what the DSP-3 itself answers, so a machine without one can still check.

The corpus this writes used to be a recording of an independent reimplementation,
made when there was nothing better to hold the model to. There is now: the part's
own microcode. Where the two disagree the part decides, so the answers come from
the part.

Two things about the old arrangement made it fragile, and both are fixed here.

Its sessions were generated by driving the model, because how many bytes a
command wants next depends on a bit the command before it set. That made the
questions a function of the model, so correcting the model changed the questions
along with the answers and nothing could be compared to anything. The sessions
are written out here as plain byte scripts instead. Once frozen they are
questions, and a question does not change because an answer did.

And it recorded only the answers. A script records what was asked as well, so a
reader can see the exchange rather than a blob whose meaning lived in a generator
that has since moved on.

Nothing in the file this produces belongs to anybody. The scripts are arithmetic
from a seed, and the answers are what the part said. Running this needs an image
of the microcode; running the corpus it produces does not, which is the whole
point of it.
"""

import base64
import json
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from snesdsp import silicon

ROOT = Path(__file__).resolve().parent

WRITE = "w"

READ = "r"

COMMANDS = (0x02, 0x03, 0x06, 0x07, 0x0C, 0x0F, 0x10, 0x18, 0x1C, 0x1E, 0x38, 0x3E)
"""Every command the part has except the one that hands back its mask ROM.

That one is left out for the reason it always was: answering it needs the mask
ROM, which is content rather than behaviour and is not shipped here.
"""

WORDS_PER_COMMAND = 4

READS_PER_COMMAND = 6

PART = "dsp3"

RECORDED_FROM = "the part's own microcode, run on the processor it is masked into"


class Usage(Exception):
    pass


def script_for(seed, command):
    """One command as a plain list of steps, decided by the seed and the command.

    One command per script, on a part that has just been started. Running all of
    them into a single part reads as a fuller test and is a worse one: the first
    command whose answer is wrong leaves the part somewhere the model is not, and
    every later command in that session is then measuring the drift rather than
    itself. One command alone says which command is wrong.

    The words are uniform on purpose. A script shaped around what a command is
    believed to want is shaped by the belief, and the belief is the thing being
    tested.
    """
    chance = random.Random(seed)
    steps = [[WRITE, command]]
    for _ in range(WORDS_PER_COMMAND):
        word = chance.randrange(0x10000)
        steps.append([WRITE, word & 0xFF])
        steps.append([WRITE, word >> 8])
    steps.extend([READ, 0] for _ in range(READS_PER_COMMAND))
    return steps


def answers_of(steps, chip):
    """What one part says when a script is played at it."""
    said = []
    for kind, value in steps:
        if kind == WRITE:
            chip.write(value)
        else:
            said.append(chip.read())
    return said


def _silicon(part=PART):
    """A real part, which needs an image and so cannot be built on a bare runner."""
    return silicon.Silicon(part)  # pragma: no cover


def record(seeds, commands=COMMANDS, build=_silicon):
    """Every command against every seed, one fresh part per script."""
    found = []
    for command in commands:
        for seed in seeds:
            steps = script_for(seed, command)
            said = answers_of(steps, build())
            found.append(
                {
                    "seed": seed,
                    "command": command,
                    "script": steps,
                    "expected": base64.b64encode(bytes(said)).decode("ascii"),
                }
            )
    return found


def write_out(where, seeds, build=_silicon):
    """The corpus file, with what it is and where its answers came from."""
    held = {
        "note": (
            "Recorded from the part itself, which is the authority on what it"
            " answers. The scripts are arithmetic from a seed and carry nothing"
            " belonging to anybody."
        ),
        "part": PART,
        "recordedFrom": RECORDED_FROM,
        "cases": record(seeds, build=build),
    }
    Path(where).write_text(json.dumps(held, indent=2) + "\n")
    return held


def main(argv, why_not=silicon.why_not, build=_silicon):
    if len(argv) < 2:
        raise Usage("usage: dsp3record.py <corpus.json> <cases>")

    reason = why_not()
    if reason:
        print(f"  nothing was recorded: {reason}")
        return 2

    where, count = argv[0], argv[1]
    if not count.isdigit():
        raise Usage(f"{count} is not a number of cases")

    held = write_out(Path(where), range(int(count)), build)
    print(f"  {len(held['cases'])} scripts recorded into {where}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except Usage as refusal:
        print(refusal)
        sys.exit(2)
