"""Replay what the part itself answered, on a machine that has no part.

The microcode is the authority on what this chip does, and running it needs an
image belonging to whoever made it. Most machines will not have one, so what the
part said is recorded once, beside the questions it was asked, and replayed
against the model everywhere afterwards. That is what holds the model honest
where the part is absent.

The recording used to come from an independent reimplementation instead, and two
things about that arrangement have changed.

Its answers came from software, and where that software and the chip disagree the
chip is right. One such disagreement is now settled: command `0x1c` was believed
to swallow two words and answer two zeroes, and the part answers the last word it
was written, over and over, for as long as it is asked.

And its questions were generated by driving the model, because how many bytes a
command wants next depends on a bit the command before it set. That made the
questions a function of the model, so correcting the model changed what was asked
as well as what came back, and nothing could be compared to anything. The
questions are plain byte scripts in the file now. A question does not change
because an answer did.

Where the model does not yet answer what the part answered, the file says so, one
index at a time. That list is a gate rather than an excuse: a fix shrinks it, a
regression grows it, and either way this check fails until somebody writes down
what changed and why.

One command is deliberately absent. The chip can hand back its own mask ROM word
by word, and a corpus that asked it to would be a copy of that ROM wearing a test
harness. Every other command is here.

Usage:
    python3 conformance/dsp3corpus.py [corpus.json]
"""

import base64
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from snesdsp import dsp3

ROOT = Path(__file__).resolve().parent

DEFAULT_CORPUS = ROOT / "dsp3corpus.json"

WRITE = "w"

READ = "r"

REPORT_LIMIT = 5


class Usage(Exception):
    pass


def load(path=None):
    """The corpus, from where it was asked for or from the one that ships."""
    with Path(path or DEFAULT_CORPUS).open() as handle:
        return json.load(handle)


def expected_of(case):
    """The bytes the part gave for one case."""
    return list(base64.b64decode(case["expected"]))


def replay(steps):
    """One script through the model."""
    chip = dsp3.Dsp3()
    answers = []
    for kind, value in steps:
        if kind == WRITE:
            chip.write(value)
        else:
            answers.append(chip.read())
    return answers


def disagreement(expected, actual):
    """The first byte the two answers differ on, or nothing."""
    for index in range(max(len(expected), len(actual))):
        theirs = expected[index] if index < len(expected) else None
        ours = actual[index] if index < len(actual) else None
        if theirs != ours:
            return index, theirs, ours
    return None


def differences(case):
    """Every index in one case where the model does not say what the part said."""
    wanted = expected_of(case)
    got = replay(case["script"])
    return tuple(
        index
        for index in range(max(len(wanted), len(got)))
        if (wanted[index] if index < len(wanted) else None)
        != (got[index] if index < len(got) else None)
    )


def names(case):
    """What identifies one case, which is its seed and the command it asked.

    Both, because the same seed is used for every command: keying on the seed
    alone silently merges twelve cases into one and hides eleven of them.
    """
    return case["seed"], case["command"]


def measured(held):
    """Where the model and the part part company right now, by case."""
    found = {}
    for case in held["cases"]:
        where = differences(case)
        if where:
            found[names(case)] = where
    return found


def recorded(held):
    """Where the file says they part company, by case."""
    return {names(one): tuple(one["indices"]) for one in held.get("knownGaps", ())}


def drifted(held):
    """Cases whose disagreement is not the one that was written down."""
    now, before = measured(held), recorded(held)
    return {
        which: (before.get(which, ()), now.get(which, ()))
        for which in sorted(set(now) | set(before))
        if now.get(which, ()) != before.get(which, ())
    }


def lines_for(held):
    """The lines a person reads."""
    cases = held["cases"]
    off = drifted(held)
    known = sum(len(one) for one in recorded(held).values())
    total = sum(len(expected_of(case)) for case in cases)

    lines = [
        f"  {len(cases)} scripts, {total} bytes compared against the part itself",
        f"  {known} of them are recorded as places the model does not match it yet",
    ]
    if not off:
        lines.append("  nothing has drifted from what was written down")
        return lines

    lines.append(f"  {len(off)} scripts no longer match what was written down:")
    for (seed, command), (before, now) in list(off.items())[:REPORT_LIMIT]:
        lines.append(
            f"    command {command:#04x} seed {seed}: was {before or 'clean'}, now {now or 'clean'}"
        )
    return lines


def main(argv):
    held = load(Path(argv[0]) if argv else None)
    for line in lines_for(held):
        print(line)
    return 1 if drifted(held) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
